name: train_openmha_bmfwf
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.11
  - numpy=1.23.5
  - pandas=2.0.0
  - resampy=0.4.2
  - matplotlib=3.7.1
  - pip
  - pip:
      - human-readable-ids==0.1.3
      - pypesq==1.2.4
      - pystoi==0.3.3
      - pesq==0.0.4
      - torchmetrics==0.11.4
      - soundfile==0.12.1
      - pyfar==0.5.3
      - lightning==2.0.6
      - jsonargparse[signatures]==4.20.0